source 'https://rubygems.org'

gem 'rails', '5.0.1'
gem 'pg', '~> 0.15'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'modernizr-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'shrine', '~> 2.5'
gem 'shrine-url'
gem 'roda'
gem 'jquery-fileupload-rails'
gem 'aws-sdk'
gem 'devise', '~> 4.2'
gem 'bootstrap', '~> 4.0.0.alpha5'
gem 'rails-assets-tether', '>= 1.1.0', source: 'https://rails-assets.org'
gem 'font-awesome-rails'
gem 'devise-bootstrap-views'
gem 'acts_as_tree'
gem 'haml'
gem 'haml-rails'

group :development, :test do
  gem 'byebug'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
